//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cyber_bot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"PnJLdaQ5aK6WieRWuazWzo7vGbaSDM7c6WnxJ4ovjQnkeRCKFU3mVYxsCjp6Zks2sVziqALriSBHoHyW8j1BYn8gH8vuWSE2vnse0GzKxzrClAgewhKwMxNz3Z9scZg7PxgYskXT91xtcJM2pNV0PDSXeVp8n14FsVVxFRtfQc3TrIQeEKxbIRmJtZ19DJz6Vs44dtvylwMOl1Hq0HCJdUIYb-yJrHxzLqb3G3CepD3kDKLImd5AGrAk9J3CdXSu3SRVYH_s2eBG7LQFkWeDvpRGIo5-1UayiGhbDYgI5kfKzzeVqeVzhK7mss-5ZstMe8n54Lh8p48EE7q-2AGrozFyzHyj6q3Vu1a8brJMmT7MlYqX0-3k0Qgv1-i0Qs3T5wVSxLcThTrT8GQTSwkvfrzUQNIdMdz5VDzXTL_8tYIhxMyoQhTmfYyflUSxOrgpS8qy3KuIFD3gy1BtjhvUNexCBOY")]
        public string masterCookie {
            get {
                return ((string)(this["masterCookie"]));
            }
            set {
                this["masterCookie"] = value;
            }
        }
    }
}
